# Generated by Django 4.1.7 on 2023-08-12 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_inscrit_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='inscrit',
            name='about',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='inscrit',
            name='function_in_school',
            field=models.CharField(choices=[('Eleve', 'Elève'), ('Etudiant', 'Etudiant'), ('Professeur', 'Professeur'), ('Independent', 'Chercheur indépendant'), ('Others', 'Autres'), ('-', '-')], default='-', max_length=20, verbose_name='Statut'),
        ),
        migrations.AlterField(
            model_name='inscrit',
            name='photo',
            field=models.ImageField(default='photos/default.jpg', upload_to='photos'),
        ),
    ]
