# Generated by Django 4.1.7 on 2023-08-12 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_inscrit_about_alter_inscrit_function_in_school_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inscrit',
            name='birth_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='inscrit',
            name='current_city',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
