# Generated by Django 4.1.7 on 2023-08-13 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_inscrit_cover_image_inscrit_created_on_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inscrit',
            name='created_on',
        ),
        migrations.AlterField(
            model_name='inscrit',
            name='cover_image',
            field=models.ImageField(default='images/default_img/cover_image.jpg', upload_to='images'),
        ),
    ]
