# Generated by Django 4.1.7 on 2023-08-13 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_remove_inscrit_created_on_alter_inscrit_cover_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inscrit',
            name='birth_date',
            field=models.DateField(null=True, verbose_name='Date de naissance'),
        ),
        migrations.AlterField(
            model_name='inscrit',
            name='cover_image',
            field=models.ImageField(default='images/default_img/cover_default.jpg', upload_to='images'),
        ),
        migrations.AlterField(
            model_name='inscrit',
            name='function_in_school',
            field=models.CharField(choices=[('Elève', 'Elève'), ('Etudiant', 'Etudiant'), ('Professeur', 'Professeur'), ('Chercheur Indépendant', 'Chercheur indépendant'), ('Others', 'Autres'), ('-', '-')], default='-', max_length=40, verbose_name='Statut'),
        ),
    ]
