# Generated by Django 4.1.7 on 2023-08-15 05:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_inscrit_birth_date_alter_inscrit_cover_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EtantEleve',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classe_del_eleve', models.CharField(choices=[('7emeEB', '7e EB'), ('8emeEB', '8e EB'), ('1ere', '1ère des Humanités'), ('2eme', '2ème des Humanités'), ('3eme', '3ème des Humanités'), ('4eme', '4ème des Humanités'), ('-', '-')], default='-', max_length=30, verbose_name="classe de l'élève")),
                ('tuteur', models.CharField(max_length=30)),
            ],
        ),
        migrations.AddField(
            model_name='inscrit',
            name='school_name',
            field=models.CharField(max_length=40, null=True, verbose_name="Nom de l'école"),
        ),
        migrations.AlterField(
            model_name='inscrit',
            name='function_in_school',
            field=models.CharField(choices=[('Elève', 'Elève'), ('Professeur', 'Professeur'), ('Directeur', 'Directeur'), ('Prefet', 'Préfet'), ('Secretaire', 'Secretaire'), ('-', '-')], default='-', max_length=40, verbose_name='Statut'),
        ),
        migrations.DeleteModel(
            name='Eleve',
        ),
        migrations.AddField(
            model_name='etanteleve',
            name='eleve',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='etanteleve',
            name='option',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.option'),
        ),
    ]
